### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by pcaversaccio**

### CODE REVIEW

**Comment by pcaversaccio** [comment]
quickly tagging @mmilenkovic @davidsrz

**Comment by krlosMata** [comment]
@cla-bot check

**Comment by krlosMata** [comment]
@cla-bot check

**Comment by pcaversaccio** [comment]
@krlosMata I can't sign the CLA somehow?

**Comment by krlosMata** [comment]
> @krlosMata I can't sign the CLA somehow?

It is only needed to read the CLA, so contributors are aware of it.
New contibutors will be added once we review the contribution and github user.
Thanks!

**Comment by jleebee** [comment]
@cla-bot check

**Comment by jleebee** [comment]
@cla-bot check

**Review by krlosMata — APPROVED** [review]
:smile_cat:

**Pull request merged**
